"""Derive a wider causal model from the streaming config, for the capacity check.

The protocol result is measured on models of about 20k and 31k parameters. The predictable
reviewer objection is that a small model leans harder on accumulated context, so the
cold-start penalty would shrink in a stronger model. The check is a capacity ladder on the
causal arm alone: the protocol gain is a within-arm quantity, so no control is needed.

Only the model block changes. Data, folds, split seed, schedule and optimizer are copied
from the source config, so the wider model is trained exactly like the one in the paper.

    python scripts/make_capacity_configs.py
"""
import os
import sys

import yaml

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.model.full_model import SleepStagingModel  # noqa: E402

SOURCE = "sleep78_streaming_causal.yaml"

VARIANTS = [
    {
        "name": "sleep78_streaming_causal_wide.yaml",
        "suffix": "wide",
        "mrcnn_channels_1": 16,
        "mrcnn_channels_2": 16,
        "tcn_channels": [64, 64, 64],
    },
    {
        "name": "sleep78_streaming_causal_xwide.yaml",
        "suffix": "xwide",
        "mrcnn_channels_1": 32,
        "mrcnn_channels_2": 32,
        "tcn_channels": [128, 128, 128],
    },
]


def build(variant):
    src_path = os.path.join("configs", SOURCE)
    with open(src_path) as handle:
        cfg = yaml.safe_load(handle)

    cfg["model"]["architecture"] = "tcn_attention"
    cfg["model"]["mrcnn_channels_1"] = variant["mrcnn_channels_1"]
    cfg["model"]["mrcnn_channels_2"] = variant["mrcnn_channels_2"]
    cfg["model"]["tcn_channels"] = variant["tcn_channels"]

    heads = cfg["model"]["attn_num_heads"]
    width = variant["tcn_channels"][-1]
    if width % heads != 0:
        raise SystemExit(f"tcn width {width} is not divisible by {heads} attention heads")

    for key in ("log_dir", "checkpoint_dir"):
        cfg["train"][key] = cfg["train"][key].replace("_causal_s42", f"_causal_{variant['suffix']}_s42")

    params = sum(p.numel() for p in SleepStagingModel(config=cfg).parameters())

    dst_path = os.path.join("configs", variant["name"])
    with open(dst_path, "w") as handle:
        handle.write(f"# Generated by scripts/make_capacity_configs.py from {SOURCE}.\n")
        handle.write(f"# Capacity check, causal arm only, {params:,} parameters.\n")
        yaml.safe_dump(cfg, handle, sort_keys=False, default_flow_style=False)

    print(f"{variant['name']:42s} params={params:>9,}  logs={cfg['train']['log_dir']}")
    return params


def main():
    baseline = sum(p.numel() for p in SleepStagingModel(
        config=yaml.safe_load(open(os.path.join("configs", SOURCE)))).parameters())
    print(f"{'baseline (paper model)':42s} params={baseline:>9,}")
    for variant in VARIANTS:
        params = build(variant)
        print(f"{'':42s}   {params / baseline:.1f}x the baseline")


if __name__ == "__main__":
    main()
