"""Derive the GRU arm configs from the TCN streaming configs.

Every key outside the model block is copied from the matching TCN config, so the two
architectures see identical data, folds, split seed, optimizer and schedule by
construction rather than by hand. Only the sequence encoder differs.

The non-causal control is bidirectional at a reduced per-direction hidden size, chosen so
the two GRU arms match on parameter count to within one percent. A bidirectional GRU at
the causal arm's hidden size carries 1.94 times the parameters, which would confound the
between-arm comparison with capacity. The script refuses to write the configs if the
match is worse than one percent.

    python scripts/make_gru_configs.py
"""
import os
import sys

import yaml

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.model.full_model import SleepStagingModel  # noqa: E402

CAUSAL_HIDDEN = 32
CONTROL_HIDDEN = 19
GRU_LAYERS = 2
GRU_DROPOUT = 0.1

PAIRS = [
    ("sleep78_streaming_causal.yaml", "sleep78_streaming_gru.yaml", True),
    ("sleep78_streaming_causal_s43.yaml", "sleep78_streaming_gru_s43.yaml", True),
    ("sleep78_streaming_causal_s44.yaml", "sleep78_streaming_gru_s44.yaml", True),
    ("sleep78_streaming_noncausal.yaml", "sleep78_streaming_gru_noncausal.yaml", False),
    ("sleep78_streaming_noncausal_s43.yaml", "sleep78_streaming_gru_noncausal_s43.yaml", False),
    ("sleep78_streaming_noncausal_s44.yaml", "sleep78_streaming_gru_noncausal_s44.yaml", False),
]


def rename(value, causal):
    """Point a run directory at the GRU arm while keeping the seed suffix."""
    if causal:
        renamed = value.replace("_causal", "_gru")
    else:
        renamed = value.replace("_noncausal", "_gru_noncausal")
    if renamed == value:
        raise SystemExit(f"could not derive a GRU run directory from {value!r}")
    return renamed


def build(src_name, dst_name, causal):
    src_path = os.path.join("configs", src_name)
    if not os.path.exists(src_path):
        raise SystemExit(f"missing source config {src_path}")
    with open(src_path) as handle:
        cfg = yaml.safe_load(handle)

    if bool(cfg["model"]["causal"]) is not causal:
        raise SystemExit(
            f"{src_name} declares causal={cfg['model']['causal']}, expected {causal}")

    cfg["model"] = {
        "architecture": "gru",
        "mrcnn_channels_1": cfg["model"]["mrcnn_channels_1"],
        "mrcnn_channels_2": cfg["model"]["mrcnn_channels_2"],
        "gru_hidden_size": CAUSAL_HIDDEN if causal else CONTROL_HIDDEN,
        "gru_num_layers": GRU_LAYERS,
        "gru_dropout": GRU_DROPOUT,
        "num_classes": cfg["model"]["num_classes"],
        "causal": causal,
    }
    for key in ("log_dir", "checkpoint_dir"):
        cfg["train"][key] = rename(cfg["train"][key], causal)

    params = sum(p.numel() for p in SleepStagingModel(config=cfg).parameters())

    dst_path = os.path.join("configs", dst_name)
    with open(dst_path, "w") as handle:
        handle.write(f"# Generated by scripts/make_gru_configs.py from {src_name}.\n")
        handle.write(f"# Recurrent encoder, {params:,} parameters. Do not edit by hand:\n")
        handle.write("# everything outside the model block must stay identical to the source.\n")
        yaml.safe_dump(cfg, handle, sort_keys=False, default_flow_style=False)

    print(f"{dst_name:44s} causal={str(causal):5s} params={params:>7,}  "
          f"logs={cfg['train']['log_dir']}")
    return params


def main():
    counts = {True: [], False: []}
    for src_name, dst_name, causal in PAIRS:
        counts[causal].append(build(src_name, dst_name, causal))

    if len(set(counts[True])) != 1 or len(set(counts[False])) != 1:
        raise SystemExit("seeds within an arm disagree on parameter count")

    causal_params = counts[True][0]
    control_params = counts[False][0]
    ratio = control_params / causal_params
    print(f"\ncausal {causal_params:,} vs control {control_params:,}, ratio {ratio:.4f}")
    if abs(ratio - 1.0) > 0.01:
        raise SystemExit(
            "the two arms differ by more than one percent on parameter count; "
            "adjust CONTROL_HIDDEN before running anything")
    print("arms match on parameter count to within one percent")


if __name__ == "__main__":
    main()
